spring:
  application:
    name: todo-app-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-app
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: huynhgiaphu2710@gmail.com
    password: zsucvppqqurluqxq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
